/**
 * Vite 插件：处理 .ovs 文件
 *
 * 功能：
 * - 拦截 .ovs 文件
 * - 转换为 Vue 函数组件
 * - 内部处理 css {} 语法生成的原子类 CSS
 */

import type { Plugin } from 'vite'
import { createFilter } from 'vite'
import { vitePluginOvsTransform, OvsCstToSlimeAstUtil } from 'ovs-compiler'
// 从 cssts 导入命名转换函数
import { getCssClassName, getCssProperty } from 'cssts/src/index.ts'

export interface OvsPluginOptions {
    /**
     * CSS 类名前缀
     */
    classPrefix?: string
}

// 虚拟 CSS 模块 ID
const VIRTUAL_CSS_ID = 'virtual:ovs-cssts.css'
const RESOLVED_VIRTUAL_CSS_ID = '\0' + VIRTUAL_CSS_ID

/**
 * 从 TS 属性名获取 CSS 值
 */
function getCssValue(atomName: string): string | undefined {
    const className = getCssClassName(atomName)
    const underscoreIndex = className.indexOf('_')
    if (underscoreIndex > 0) {
        let value = className.slice(underscoreIndex + 1)
        value = value.replace(/\\\./g, '.').replace(/\\%/g, '%').replace(/\\\//g, '/')
        return value
    }
    return undefined
}

/**
 * 生成单个原子类的 CSS 规则
 */
function generateAtomCssRule(atomName: string, prefix: string = ''): string | null {
    const className = getCssClassName(atomName)
    const property = getCssProperty(atomName)
    const value = getCssValue(atomName)

    if (!property || !value) {
        return null
    }

    const fullClassName = prefix ? `${prefix}${className}` : className
    return `.${fullClassName} { ${property}: ${value}; }`
}

/**
 * 生成所有使用的原子类的 CSS
 */
function generateUsedAtomsCss(usedAtoms: Set<string>, prefix: string = ''): string {
    const lines: string[] = [
        '/* Auto-generated by vite-plugin-ovs */',
        '',
    ]

    const grouped = new Map<string, string[]>()

    for (const atomName of usedAtoms) {
        const rule = generateAtomCssRule(atomName, prefix)
        if (rule) {
            const property = getCssProperty(atomName) || 'other'
            if (!grouped.has(property)) {
                grouped.set(property, [])
            }
            grouped.get(property)!.push(rule)
        }
    }

    const sortedProperties = [...grouped.keys()].sort()
    for (const property of sortedProperties) {
        lines.push(`/* ${property} */`)
        const rules = grouped.get(property)!.sort()
        lines.push(...rules)
        lines.push('')
    }

    return lines.join('\n')
}

/**
 * 包装 OVS class 组件为 Vue 组件
 * 
 * OVS class 组件有 render() 方法，需要被包装成 Vue 组件才能在 Vue 中使用。
 * 
 * 输入: export class MyComponent { render() { ... } }
 * 输出: 
 *   import { defineComponent, reactive } from 'vue';
 *   class MyComponent { render() { ... } }
 *   export { MyComponent as _OvsClass_MyComponent };
 *   export const MyComponent = defineComponent({ ... });
 */
function wrapOvsClassComponents(code: string): string {
    // 匹配 export class ClassName { ... render() { ... } }
    const classExportRegex = /export\s+class\s+(\w+)\s*\{/g
    const matches = [...code.matchAll(classExportRegex)]
    
    if (matches.length === 0) {
        return code
    }

    // 检查是否已经有 Vue 导入
    const hasVueImport = /import\s*\{[^}]*defineComponent[^}]*\}\s*from\s*['"]vue['"]/.test(code)
    
    let result = code
    const classNames: string[] = []
    
    for (const match of matches) {
        const className = match[1]
        classNames.push(className)
        
        // 将 export class 改为 class（移除 export）
        result = result.replace(
            new RegExp(`export\\s+class\\s+${className}\\s*\\{`),
            `class _OvsClass_${className} {`
        )
    }
    
    // 添加 Vue 导入（如果需要）
    if (!hasVueImport) {
        result = `import { defineComponent, reactive, h } from 'vue';\n` + result
    }
    
    // 为每个 class 添加 Vue 组件包装
    for (const className of classNames) {
        const wrapperCode = `
// OVS class 组件包装
export const ${className} = defineComponent({
    name: '${className}',
    setup(props, { slots }) {
        const instance = reactive(new _OvsClass_${className}());
        return () => {
            const result = instance.render();
            return result;
        };
    }
});
`
        result += wrapperCode
    }
    
    return result
}

/**
 * OVS Vite 插件
 * 
 * 单一插件，内部处理：
 * - .ovs 文件转换为 Vue 组件
 * - css {} 语法生成的原子类 CSS
 */
export default function vitePluginOvs(options: OvsPluginOptions = {}): Plugin {
    const filter = createFilter(/\.ovs$/, null)
    const prefix = options.classPrefix || ''
    
    // 收集使用的原子类
    const usedAtoms = new Set<string>()

    return {
        name: 'vite-plugin-ovs',
        enforce: 'pre',

        // 解析虚拟 CSS 模块
        resolveId(id) {
            if (id === VIRTUAL_CSS_ID) {
                return RESOLVED_VIRTUAL_CSS_ID
            }
        },

        // 加载虚拟 CSS 模块内容
        load(id) {
            if (id === RESOLVED_VIRTUAL_CSS_ID) {
                return generateUsedAtomsCss(usedAtoms, prefix)
            }
        },

        transform(code, id) {
            if (!filter(id)) {
                return
            }

            // 转换 OVS 代码
            const res = vitePluginOvsTransform(code)

            // 收集使用的原子类
            const atoms = OvsCstToSlimeAstUtil.getUsedAtoms()
            for (const atom of atoms) {
                usedAtoms.add(atom)
            }

            // 注入虚拟 CSS 模块的导入
            let transformedCode = res.code
            if (atoms.size > 0 && !transformedCode.includes(VIRTUAL_CSS_ID)) {
                transformedCode = `import '${VIRTUAL_CSS_ID}'\n` + transformedCode
            }

            // 包装 OVS class 组件为 Vue 组件
            // 检测 export class XXX { ... render() { ... } } 模式
            transformedCode = wrapOvsClassComponents(transformedCode)

            return {
                code: transformedCode,
                map: null
            }
        },

        // HMR 支持
        handleHotUpdate({ file, server }) {
            if (file.endsWith('.ovs')) {
                // 触发虚拟 CSS 模块更新
                const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_CSS_ID)
                if (mod) {
                    server.moduleGraph.invalidateModule(mod)
                }
                server.ws.send({ type: 'full-reload' })
            }
        }
    }
}

export { vitePluginOvs, VIRTUAL_CSS_ID }
