/**
 * Vite 插件：处理 .ovs 文件
 *
 * 功能：
 * - 拦截 .ovs 文件
 * - 转换为 Vue 函数组件
 * - 内部处理 css {} 语法生成的原子类 CSS
 */

import type { Plugin } from 'vite'
import { createFilter } from 'vite'
import { vitePluginOvsTransform, OvsCstToSlimeAstUtil } from 'ovs-compiler'
// 从 cssts 导入命名转换函数
import { getCssClassName, getCssProperty } from 'cssts/src/index.ts'

export interface OvsPluginOptions {
    /**
     * CSS 类名前缀
     */
    classPrefix?: string
}

// 虚拟 CSS 模块 ID
const VIRTUAL_CSS_ID = 'virtual:ovs-cssts.css'
const RESOLVED_VIRTUAL_CSS_ID = '\0' + VIRTUAL_CSS_ID

/**
 * 从 TS 属性名获取 CSS 值
 */
function getCssValue(atomName: string): string | undefined {
    const className = getCssClassName(atomName)
    const underscoreIndex = className.indexOf('_')
    if (underscoreIndex > 0) {
        let value = className.slice(underscoreIndex + 1)
        value = value.replace(/\\\./g, '.').replace(/\\%/g, '%').replace(/\\\//g, '/')
        return value
    }
    return undefined
}

/**
 * 生成单个原子类的 CSS 规则
 */
function generateAtomCssRule(atomName: string, prefix: string = ''): string | null {
    const className = getCssClassName(atomName)
    const property = getCssProperty(atomName)
    const value = getCssValue(atomName)

    if (!property || !value) {
        return null
    }

    const fullClassName = prefix ? `${prefix}${className}` : className
    return `.${fullClassName} { ${property}: ${value}; }`
}

/**
 * 生成所有使用的原子类的 CSS
 */
function generateUsedAtomsCss(usedAtoms: Set<string>, prefix: string = ''): string {
    const lines: string[] = [
        '/* Auto-generated by vite-plugin-ovs */',
        '',
    ]

    const grouped = new Map<string, string[]>()

    for (const atomName of usedAtoms) {
        const rule = generateAtomCssRule(atomName, prefix)
        if (rule) {
            const property = getCssProperty(atomName) || 'other'
            if (!grouped.has(property)) {
                grouped.set(property, [])
            }
            grouped.get(property)!.push(rule)
        }
    }

    const sortedProperties = [...grouped.keys()].sort()
    for (const property of sortedProperties) {
        lines.push(`/* ${property} */`)
        const rules = grouped.get(property)!.sort()
        lines.push(...rules)
        lines.push('')
    }

    return lines.join('\n')
}

/**
 * OVS Vite 插件
 * 
 * 单一插件，内部处理：
 * - .ovs 文件转换为 Vue 组件
 * - css {} 语法生成的原子类 CSS
 */
export default function vitePluginOvs(options: OvsPluginOptions = {}): Plugin {
    const filter = createFilter(/\.ovs$/, null)
    const prefix = options.classPrefix || ''
    
    // 收集使用的原子类
    const usedAtoms = new Set<string>()

    return {
        name: 'vite-plugin-ovs',
        enforce: 'pre',

        // 解析虚拟 CSS 模块
        resolveId(id) {
            if (id === VIRTUAL_CSS_ID) {
                return RESOLVED_VIRTUAL_CSS_ID
            }
        },

        // 加载虚拟 CSS 模块内容
        load(id) {
            if (id === RESOLVED_VIRTUAL_CSS_ID) {
                return generateUsedAtomsCss(usedAtoms, prefix)
            }
        },

        transform(code, id) {
            if (!filter(id)) {
                return
            }

            // 转换 OVS 代码
            const res = vitePluginOvsTransform(code)

            // 收集使用的原子类
            const atoms = OvsCstToSlimeAstUtil.getUsedAtoms()
            for (const atom of atoms) {
                usedAtoms.add(atom)
            }

            // 注入虚拟 CSS 模块的导入
            let transformedCode = res.code
            if (atoms.size > 0 && !transformedCode.includes(VIRTUAL_CSS_ID)) {
                transformedCode = `import '${VIRTUAL_CSS_ID}'\n` + transformedCode
            }

            return {
                code: transformedCode,
                map: null
            }
        },

        // HMR 支持
        handleHotUpdate({ file, server }) {
            if (file.endsWith('.ovs')) {
                // 触发虚拟 CSS 模块更新
                const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_CSS_ID)
                if (mod) {
                    server.moduleGraph.invalidateModule(mod)
                }
                server.ws.send({ type: 'full-reload' })
            }
        }
    }
}

export { vitePluginOvs, VIRTUAL_CSS_ID }
