export const ovsInheritedSyntaxSource = [
  'object NestedLabeler {',
  '  label(name: string, premium: boolean, active: boolean): string {',
  '    const base = "hello "',
  '    if (active) {',
  '      if (premium) {',
  '        const label = "vip "',
  '        return label + name',
  '      }',
  '      const standard = "std "',
  '      return standard + name',
  '    }',
  '    return base + name',
  '  }',
  '  risky(flag: boolean): string {',
  '    try {',
  '      if (flag) {',
  '        throw new Error("boom")',
  '      }',
  '      return "ok"',
  '    } catch (error) {',
  '      return "caught"',
  '    }',
  '  }',
  '  count(limit: number): number {',
  '    let total = 0',
  '    while (total < limit) {',
  '      total = total + 1',
  '    }',
  '    return total',
  '  }',
  '  sum(limit: number): number {',
  '    let total = 0',
  '    for (let i = 0; i < limit; i = i + 1) {',
  '      if (i == 2) {',
  '        continue',
  '      }',
  '      if (i == 5) {',
  '        break',
  '      }',
  '      total = total + i',
  '    }',
  '    return total',
  '  }',
  '  countAtLeastOnce(limit: number): number {',
  '    let i = 0',
  '    do {',
  '      i = i + 1',
  '    } while (i < limit)',
  '    return i',
  '  }',
  '  collect(values: List): number {',
  '    let total = 0',
  '    for (const item of values) {',
  '      total = total + item',
  '    }',
  '    return total',
  '  }',
  '  switchStatus(status: string): string {',
  '    switch (status) {',
  '      case "ready":',
  '        return "Ready"',
  '      case "done":',
  '        return "Done"',
  '      default:',
  '        return "Unknown"',
  '    }',
  '  }',
  '}',
  'const title = "Qin"',
  'export interface ChainUser {',
  '  id: string',
  '  active?: boolean',
  '}',
  'export type ChainPair<T, U> = { left: T, right: U }',
  'class ChainService {',
  '  name: string = "qin"',
  '  count = 0',
  '  constructor(name: string) {',
  '    this.name = name',
  '  }',
  '  label(): string {',
  '    return this.name',
  '  }',
  '}',
  'const config = { name: "qin", values: [1, 2, 3] }',
  'const { name: destructuredName, values: [firstValue] } = config',
  'const optionalName = user?.profile?.name',
  'const fallbackName = user.name ?? "anonymous"',
  'const templateName = `hello ${name}`',
  'const moduleUrl = import.meta.url',
  'const loadedModule = import("./dep.qin")',
  'div(class = css { displayFlex }) {',
  '  h1 { title }',
  '}',
  '',
].join('\n')
