import type { Plugin } from 'vite'
// Development imports - use relative paths in monorepo (新结构)
import { CssTsParser } from '../../cssts/packages/cssts-compiler/src/parser/index.ts'
import { CssTsCstToAst, type CssStyleInfo } from '../../cssts/packages/cssts-compiler/src/factory/index.ts'
import { generateCssClsInterface, generateCssClsStyles } from '../../cssts/packages/cssts-compiler/src/utils/cssUtils.ts'
import SlimeGenerator from '../../slime/packages/slime-generator/src/SlimeGenerator.ts'
import * as fs from 'node:fs'
import * as path from 'node:path'

// 导入运行时的命名转换函数
import { getCssClassName, getCssProperty } from '../../cssts/packages/cssts-runtime/src/index.ts'

export interface CssTsPluginOptions {
  /**
   * 生成的类型文件路径
   * @default 'src/cssts/CssCls.d.ts'
   */
  dtsOutput?: string

  /**
   * 生成的样式文件路径
   * @default 'src/cssts/CssCls.styles.ts'
   */
  stylesOutput?: string

  /**
   * 生成的原子类文件路径
   * @default 'src/cssts/CsstsAtom.ts'
   */
  atomOutput?: string

  /**
   * 是否在开发模式下自动生成文件
   * @default true
   */
  autoGenerate?: boolean

  /**
   * 是否自动转换 Vue template 中的 :class 语法
   * @default true
   */
  transformClass?: boolean

  /**
   * cssts runtime 的导入路径
   * @default './cssts/runtime'
   */
  runtimeImport?: string

  /**
   * csstsAtom 的导入路径
   * @default './cssts/CsstsAtom'
   */
  atomImport?: string

  /**
   * CSS 类名前缀
   * 例如: 'cu-' 会生成 'cu-flex', 'cu-color-red' 等
   * @default '' (无前缀)
   */
  classPrefix?: string

  /**
   * 外部传入的原子类收集器
   * 用于与其他插件（如 vite-plugin-ovs）共享原子类收集
   * 如果不传，使用内部默认的全局收集器
   */
  usedAtoms?: Set<string>
}

// ==================== 虚拟模块 ====================

const VIRTUAL_CSS_ID = 'virtual:cssts.css'
const RESOLVED_VIRTUAL_CSS_ID = '\0' + VIRTUAL_CSS_ID

/**
 * 全局样式收集器
 */
const globalStyles = new Map<string, CssStyleInfo>()

/**
 * 全局原子类收集器
 */
const globalUsedAtoms = new Set<string>()

// ==================== CSS 生成 ====================

/**
 * CssTs 原子类命名规范（来自 cssts-types/README.md）
 * 
 * CSS 类名格式：`{property}_{value}`
 * - 用 `_` 下划线分隔属性和值
 * - 属性名使用 kebab-case（如 justify-content）
 * - 值使用 kebab-case（如 flex-start）
 * 
 * 示例：
 * - displayFlex → .display_flex { display: flex; }
 * - justifyContentCenter → .justify-content_center { justify-content: center; }
 * - paddingTop16px → .padding-top_16px { padding-top: 16px; }
 * 
 * 特殊符号转义（CSS 类名中）：
 * - 小数点：\.（如 .line-height_1\.5）
 * - 百分号：\%（如 .width_50\%）
 * - 斜杠：\/（如 .aspect-ratio_16\/9）
 */

/**
 * 从 TS 属性名获取 CSS 值
 */
function getCssValue(atomName: string): string | undefined {
  const className = getCssClassName(atomName)
  // 类名格式: property_value
  const underscoreIndex = className.indexOf('_')
  if (underscoreIndex > 0) {
    let value = className.slice(underscoreIndex + 1)
    // 反转义：将 CSS 转义符号还原为实际值
    value = value.replace(/\\\./g, '.').replace(/\\%/g, '%').replace(/\\\//g, '/')
    return value
  }
  return undefined
}

/**
 * 生成单个原子类的 CSS 规则
 * 
 * 使用 property_value 命名规范
 */
function generateAtomCssRule(atomName: string, prefix: string = ''): string | null {
  const className = getCssClassName(atomName)
  const property = getCssProperty(atomName)
  const value = getCssValue(atomName)

  if (!property || !value) {
    return null
  }

  // 添加前缀
  const fullClassName = prefix ? `${prefix}${className}` : className

  return `.${fullClassName} { ${property}: ${value}; }`
}

/**
 * 生成所有使用的原子类的 CSS
 */
function generateUsedAtomsCss(usedAtoms: Set<string>, prefix: string = ''): string {
  const lines: string[] = [
    '/* Auto-generated by vite-plugin-cssts */',
    '/* Do not edit manually */',
    '',
  ]

  // 按属性分组
  const grouped = new Map<string, string[]>()

  for (const atomName of usedAtoms) {
    const rule = generateAtomCssRule(atomName, prefix)
    if (rule) {
      const property = getCssProperty(atomName) || 'other'
      if (!grouped.has(property)) {
        grouped.set(property, [])
      }
      grouped.get(property)!.push(rule)
    }
  }

  // 按属性名排序输出
  const sortedProperties = [...grouped.keys()].sort()
  for (const property of sortedProperties) {
    lines.push(`/* ${property} */`)
    const rules = grouped.get(property)!.sort()
    lines.push(...rules)
    lines.push('')
  }

  return lines.join('\n')
}

// ==================== 文件转换 ====================

/**
 * 转换 .cssts 文件
 */
function transformCssTs(
  code: string,
  _id: string,
): { code: string; styles: Map<string, CssStyleInfo>; usedAtoms: Set<string> } {
  const parser = new CssTsParser(code)
  const cst = parser.Program()

  const transformer = new CssTsCstToAst()
  const ast = transformer.toProgram(cst)

  // 获取收集的样式和原子类
  const styles = transformer.getCssStyles()
  const usedAtoms = transformer.getUsedAtoms()

  // 生成 JavaScript 代码
  const tokens = parser.parsedTokens
  const result = SlimeGenerator.generator(ast, tokens)

  return {
    code: result.code,
    styles,
    usedAtoms,
  }
}

/**
 * 生成 CsstsAtom.ts 文件内容
 */
function generateCsstsAtomFile(usedAtoms: Set<string>, prefix: string = ''): string {
  const lines: string[] = [
    '// Auto-generated by vite-plugin-cssts',
    '// Do not edit manually',
    '',
    "import type { CsstsAtoms } from 'cssts-types'",
    '',
    '/**',
    ' * CsstsAtom 实现类',
    ' * 包含项目中使用的所有原子类',
    ' */',
    'class CsstsAtomImpl implements Partial<CsstsAtoms> {',
  ]

  // 生成每个原子类属性
  const sortedAtoms = Array.from(usedAtoms).sort()
  for (const atom of sortedAtoms) {
    const className = getCssClassName(atom)
    const fullClassName = prefix ? `${prefix}${className}` : className
    lines.push(`  readonly ${atom} = { '${fullClassName}': true } as const`)
  }

  lines.push('}')
  lines.push('')
  lines.push('/** 原子类实例 */')
  lines.push('export const csstsAtom = new CsstsAtomImpl()')
  lines.push('')
  lines.push('export default csstsAtom')

  return lines.join('\n')
}

/**
 * 生成输出文件
 */
function generateOutputFiles(
  styles: Map<string, CssStyleInfo>,
  usedAtoms: Set<string>,
  root: string,
  options: CssTsPluginOptions,
) {
  const dtsPath = path.resolve(root, options.dtsOutput || 'src/cssts/CssCls.d.ts')
  const stylesPath = path.resolve(root, options.stylesOutput || 'src/cssts/CssCls.styles.ts')
  const atomPath = path.resolve(root, options.atomOutput || 'src/cssts/CsstsAtom.ts')
  const prefix = options.classPrefix || ''

  // 确保目录存在
  const dtsDir = path.dirname(dtsPath)
  const stylesDir = path.dirname(stylesPath)
  const atomDir = path.dirname(atomPath)

  if (!fs.existsSync(dtsDir)) {
    fs.mkdirSync(dtsDir, { recursive: true })
  }
  if (!fs.existsSync(stylesDir)) {
    fs.mkdirSync(stylesDir, { recursive: true })
  }
  if (!fs.existsSync(atomDir)) {
    fs.mkdirSync(atomDir, { recursive: true })
  }

  // 生成文件（传入前缀配置）
  const dtsContent = generateCssClsInterface(styles, prefix)
  const stylesContent = generateCssClsStyles(styles, prefix)
  const atomContent = generateCsstsAtomFile(usedAtoms, prefix)

  fs.writeFileSync(dtsPath, dtsContent, 'utf-8')
  fs.writeFileSync(stylesPath, stylesContent, 'utf-8')
  fs.writeFileSync(atomPath, atomContent, 'utf-8')

  console.log(`[cssts] Generated ${dtsPath}`)
  console.log(`[cssts] Generated ${stylesPath}`)
  console.log(`[cssts] Generated ${atomPath}`)
}

// ==================== Vue Template 转换 ====================

/**
 * 转换 Vue template 中的 :class 语法
 */
function transformVueTemplate(
  code: string,
  runtimeImport: string,
): { code: string; transformed: boolean } {
  let transformed = false

  const classBindingRegex = /(:class|v-bind:class)="([^"]+)"/g

  let newCode = code.replace(classBindingRegex, (match, attr, expr) => {
    if (expr.includes('cssts.$cls')) {
      return match
    }

    const trimmedExpr = expr.trim()
    if (trimmedExpr.startsWith('{') || trimmedExpr.startsWith('[')) {
      return match
    }

    if (hasTopLevelComma(expr)) {
      transformed = true
      return `${attr}="cssts.$cls(${expr})"`
    }

    return match
  })

  if (transformed) {
    newCode = injectCsstsImport(newCode, runtimeImport)
  }

  return { code: newCode, transformed }
}

/**
 * 检查表达式是否有顶层逗号
 */
function hasTopLevelComma(expr: string): boolean {
  let depth = 0
  let inString = false
  let stringChar = ''

  for (let i = 0; i < expr.length; i++) {
    const char = expr[i]
    const prevChar = i > 0 ? expr[i - 1] : ''

    if ((char === '"' || char === "'" || char === '`') && prevChar !== '\\') {
      if (!inString) {
        inString = true
        stringChar = char
      } else if (char === stringChar) {
        inString = false
      }
      continue
    }

    if (inString) continue

    if (char === '(' || char === '[' || char === '{') {
      depth++
    } else if (char === ')' || char === ']' || char === '}') {
      depth--
    } else if (char === ',' && depth === 0) {
      return true
    }
  }

  return false
}

/**
 * 注入 cssts import
 */
function injectCsstsImport(code: string, runtimeImport: string): string {
  if (code.includes(`from '${runtimeImport}'`) || code.includes(`from "${runtimeImport}"`)) {
    return code
  }

  const scriptSetupMatch = code.match(/<script\s+setup[^>]*>/i)
  if (scriptSetupMatch) {
    const insertPos = scriptSetupMatch.index! + scriptSetupMatch[0].length
    const importStatement = `\nimport { cssts } from '${runtimeImport}'`
    return code.slice(0, insertPos) + importStatement + code.slice(insertPos)
  }

  const scriptMatch = code.match(/<script[^>]*>/i)
  if (scriptMatch) {
    const insertPos = scriptMatch.index! + scriptMatch[0].length
    const importStatement = `\nimport { cssts } from '${runtimeImport}'`
    return code.slice(0, insertPos) + importStatement + code.slice(insertPos)
  }

  return code
}

/**
 * 注入 csstsAtom import
 */
function injectCsstsAtomImport(code: string, atomImport: string): string {
  if (code.includes('csstsAtom') && code.includes(atomImport)) {
    return code
  }

  const importStatement = `import { csstsAtom } from '${atomImport}'\n`
  return importStatement + code
}

// ==================== Vite Plugin ====================

/**
 * Vite Plugin for CssTs
 */
export default function cssTsPlugin(options: CssTsPluginOptions = {}): Plugin {
  let root = ''
  let isDev = false
  const runtimeImport = options.runtimeImport || './cssts/runtime'
  const prefix = options.classPrefix || ''
  // 使用外部传入的 usedAtoms 或默认的全局收集器
  const usedAtoms = options.usedAtoms ?? globalUsedAtoms

  return {
    name: 'vite-plugin-cssts',
    enforce: 'pre',

    configResolved(config) {
      root = config.root
      isDev = config.command === 'serve'
    },

    // 解析虚拟模块
    resolveId(id) {
      if (id === VIRTUAL_CSS_ID) {
        return RESOLVED_VIRTUAL_CSS_ID
      }
    },

    // 加载虚拟模块内容
    load(id) {
      if (id === RESOLVED_VIRTUAL_CSS_ID) {
        // 生成使用的原子类的 CSS（使用实例级的 usedAtoms）
        return generateUsedAtomsCss(usedAtoms, prefix)
      }
    },

    transform(code, id) {
      // 处理 .vue 文件的 :class 转换
      if (id.endsWith('.vue') && options.transformClass !== false) {
        const result = transformVueTemplate(code, runtimeImport)
        if (result.transformed) {
          return {
            code: result.code,
            map: null,
          }
        }
      }

      // 处理 .cssts 文件
      if (id.endsWith('.cssts')) {
        try {
          const result = transformCssTs(code, id)

          // 合并到全局样式
          for (const [name, info] of result.styles) {
            globalStyles.set(name, info)
          }

          // 合并到全局原子类
          for (const atom of result.usedAtoms) {
            globalUsedAtoms.add(atom)
          }

          // 注入 csstsAtom import
          let transformedCode = result.code
          if (result.usedAtoms.size > 0) {
            const atomImport = options.atomImport || './cssts/CsstsAtom'
            transformedCode = injectCsstsAtomImport(transformedCode, atomImport)
          }

          // 在开发模式下自动生成文件
          if (isDev && options.autoGenerate !== false) {
            generateOutputFiles(globalStyles, globalUsedAtoms, root, options)
          }

          return {
            code: transformedCode,
            map: null,
          }
        } catch (e: any) {
          console.error(`[cssts] Error transforming ${id}:`, e.message)
          throw e
        }
      }

      return null
    },

    // 开发模式下，当原子类变化时触发 HMR
    handleHotUpdate({ file, server }) {
      if (file.endsWith('.cssts')) {
        // 触发虚拟 CSS 模块更新
        const mod = server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_CSS_ID)
        if (mod) {
          server.moduleGraph.invalidateModule(mod)
          return [mod]
        }
      }
    },

    buildEnd() {
      // 构建结束时生成文件
      if (globalStyles.size > 0 || globalUsedAtoms.size > 0) {
        generateOutputFiles(globalStyles, globalUsedAtoms, root, options)
      }
    },
  }
}

export { transformCssTs, transformVueTemplate, generateOutputFiles, globalStyles, globalUsedAtoms, VIRTUAL_CSS_ID }
