/**
 * CssTs Global Type Declarations
 * 
 * 自动生成，请勿手动修改
 * 生成时间: 2025-12-12T04:51:11.663Z
 * 数据来源: css-tree
 */

import type { CsstsAtoms } from './CsstsAtoms'
import type { CsstsRuntime } from './runtime'

declare global {
  /** CssTs runtime */
  const cssts: CsstsRuntime

  // ==================== display ====================
  const displayBlock: CsstsAtoms['displayBlock']
  const displayContents: CsstsAtoms['displayContents']
  const displayFlex: CsstsAtoms['displayFlex']
  const displayFlow: CsstsAtoms['displayFlow']
  const displayFlowRoot: CsstsAtoms['displayFlowRoot']
  const displayGrid: CsstsAtoms['displayGrid']
  const displayInline: CsstsAtoms['displayInline']
  const displayInlineBlock: CsstsAtoms['displayInlineBlock']
  const displayInlineFlex: CsstsAtoms['displayInlineFlex']
  const displayInlineGrid: CsstsAtoms['displayInlineGrid']
  const displayInlineListItem: CsstsAtoms['displayInlineListItem']
  const displayInlineTable: CsstsAtoms['displayInlineTable']
  const displayListItem: CsstsAtoms['displayListItem']
  const displayNone: CsstsAtoms['displayNone']
  const displayRuby: CsstsAtoms['displayRuby']
  const displayRubyBase: CsstsAtoms['displayRubyBase']
  const displayRubyBaseContainer: CsstsAtoms['displayRubyBaseContainer']
  const displayRubyText: CsstsAtoms['displayRubyText']
  const displayRubyTextContainer: CsstsAtoms['displayRubyTextContainer']
  const displayRunIn: CsstsAtoms['displayRunIn']
  const displayTable: CsstsAtoms['displayTable']
  const displayTableCaption: CsstsAtoms['displayTableCaption']
  const displayTableCell: CsstsAtoms['displayTableCell']
  const displayTableColumn: CsstsAtoms['displayTableColumn']
  const displayTableColumnGroup: CsstsAtoms['displayTableColumnGroup']
  const displayTableFooterGroup: CsstsAtoms['displayTableFooterGroup']
  const displayTableHeaderGroup: CsstsAtoms['displayTableHeaderGroup']
  const displayTableRow: CsstsAtoms['displayTableRow']
  const displayTableRowGroup: CsstsAtoms['displayTableRowGroup']

  // ==================== position ====================
  const positionAbsolute: CsstsAtoms['positionAbsolute']
  const positionFixed: CsstsAtoms['positionFixed']
  const positionRelative: CsstsAtoms['positionRelative']
  const positionStatic: CsstsAtoms['positionStatic']
  const positionSticky: CsstsAtoms['positionSticky']

  // ==================== float ====================
  const floatInlineEnd: CsstsAtoms['floatInlineEnd']
  const floatInlineStart: CsstsAtoms['floatInlineStart']
  const floatLeft: CsstsAtoms['floatLeft']
  const floatNone: CsstsAtoms['floatNone']
  const floatRight: CsstsAtoms['floatRight']

  // ==================== clear ====================
  const clearBoth: CsstsAtoms['clearBoth']
  const clearInlineEnd: CsstsAtoms['clearInlineEnd']
  const clearInlineStart: CsstsAtoms['clearInlineStart']
  const clearLeft: CsstsAtoms['clearLeft']
  const clearNone: CsstsAtoms['clearNone']
  const clearRight: CsstsAtoms['clearRight']

  // ==================== flex-direction ====================
  const flexDirectionColumn: CsstsAtoms['flexDirectionColumn']
  const flexDirectionColumnReverse: CsstsAtoms['flexDirectionColumnReverse']
  const flexDirectionRow: CsstsAtoms['flexDirectionRow']
  const flexDirectionRowReverse: CsstsAtoms['flexDirectionRowReverse']

  // ==================== flex-wrap ====================
  const flexWrapNowrap: CsstsAtoms['flexWrapNowrap']
  const flexWrapWrap: CsstsAtoms['flexWrapWrap']
  const flexWrapWrapReverse: CsstsAtoms['flexWrapWrapReverse']

  // ==================== flex-grow ====================
  const flexGrow0: CsstsAtoms['flexGrow0']
  const flexGrow1: CsstsAtoms['flexGrow1']

  // ==================== flex-shrink ====================
  const flexShrink0: CsstsAtoms['flexShrink0']
  const flexShrink1: CsstsAtoms['flexShrink1']

  // ==================== flex-basis ====================
  const flexBasisContent: CsstsAtoms['flexBasisContent']

  // ==================== justify-content ====================
  const justifyContentCenter: CsstsAtoms['justifyContentCenter']
  const justifyContentEnd: CsstsAtoms['justifyContentEnd']
  const justifyContentFlexEnd: CsstsAtoms['justifyContentFlexEnd']
  const justifyContentFlexStart: CsstsAtoms['justifyContentFlexStart']
  const justifyContentLeft: CsstsAtoms['justifyContentLeft']
  const justifyContentNormal: CsstsAtoms['justifyContentNormal']
  const justifyContentRight: CsstsAtoms['justifyContentRight']
  const justifyContentSafe: CsstsAtoms['justifyContentSafe']
  const justifyContentSpaceAround: CsstsAtoms['justifyContentSpaceAround']
  const justifyContentSpaceBetween: CsstsAtoms['justifyContentSpaceBetween']
  const justifyContentSpaceEvenly: CsstsAtoms['justifyContentSpaceEvenly']
  const justifyContentStart: CsstsAtoms['justifyContentStart']
  const justifyContentStretch: CsstsAtoms['justifyContentStretch']
  const justifyContentUnsafe: CsstsAtoms['justifyContentUnsafe']

  // ==================== align-items ====================
  const alignItemsBaseline: CsstsAtoms['alignItemsBaseline']
  const alignItemsCenter: CsstsAtoms['alignItemsCenter']
  const alignItemsEnd: CsstsAtoms['alignItemsEnd']
  const alignItemsFirst: CsstsAtoms['alignItemsFirst']
  const alignItemsFlexEnd: CsstsAtoms['alignItemsFlexEnd']
  const alignItemsFlexStart: CsstsAtoms['alignItemsFlexStart']
  const alignItemsLast: CsstsAtoms['alignItemsLast']
  const alignItemsNormal: CsstsAtoms['alignItemsNormal']
  const alignItemsSafe: CsstsAtoms['alignItemsSafe']
  const alignItemsSelfEnd: CsstsAtoms['alignItemsSelfEnd']
  const alignItemsSelfStart: CsstsAtoms['alignItemsSelfStart']
  const alignItemsStart: CsstsAtoms['alignItemsStart']
  const alignItemsStretch: CsstsAtoms['alignItemsStretch']
  const alignItemsUnsafe: CsstsAtoms['alignItemsUnsafe']

  // ==================== align-self ====================
  const alignSelfAuto: CsstsAtoms['alignSelfAuto']
  const alignSelfBaseline: CsstsAtoms['alignSelfBaseline']
  const alignSelfCenter: CsstsAtoms['alignSelfCenter']
  const alignSelfEnd: CsstsAtoms['alignSelfEnd']
  const alignSelfFirst: CsstsAtoms['alignSelfFirst']
  const alignSelfFlexEnd: CsstsAtoms['alignSelfFlexEnd']
  const alignSelfFlexStart: CsstsAtoms['alignSelfFlexStart']
  const alignSelfLast: CsstsAtoms['alignSelfLast']
  const alignSelfNormal: CsstsAtoms['alignSelfNormal']
  const alignSelfSafe: CsstsAtoms['alignSelfSafe']
  const alignSelfSelfEnd: CsstsAtoms['alignSelfSelfEnd']
  const alignSelfSelfStart: CsstsAtoms['alignSelfSelfStart']
  const alignSelfStart: CsstsAtoms['alignSelfStart']
  const alignSelfStretch: CsstsAtoms['alignSelfStretch']
  const alignSelfUnsafe: CsstsAtoms['alignSelfUnsafe']

  // ==================== align-content ====================
  const alignContentBaseline: CsstsAtoms['alignContentBaseline']
  const alignContentCenter: CsstsAtoms['alignContentCenter']
  const alignContentEnd: CsstsAtoms['alignContentEnd']
  const alignContentFirst: CsstsAtoms['alignContentFirst']
  const alignContentFlexEnd: CsstsAtoms['alignContentFlexEnd']
  const alignContentFlexStart: CsstsAtoms['alignContentFlexStart']
  const alignContentLast: CsstsAtoms['alignContentLast']
  const alignContentNormal: CsstsAtoms['alignContentNormal']
  const alignContentSafe: CsstsAtoms['alignContentSafe']
  const alignContentSpaceAround: CsstsAtoms['alignContentSpaceAround']
  const alignContentSpaceBetween: CsstsAtoms['alignContentSpaceBetween']
  const alignContentSpaceEvenly: CsstsAtoms['alignContentSpaceEvenly']
  const alignContentStart: CsstsAtoms['alignContentStart']
  const alignContentStretch: CsstsAtoms['alignContentStretch']
  const alignContentUnsafe: CsstsAtoms['alignContentUnsafe']

  // ==================== order ====================
  const order1: CsstsAtoms['order1']
  const order0: CsstsAtoms['order0']
  const order2: CsstsAtoms['order2']
  const order3: CsstsAtoms['order3']
  const order4: CsstsAtoms['order4']
  const order5: CsstsAtoms['order5']

  // ==================== width ====================
  const widthAuto: CsstsAtoms['widthAuto']
  const widthFitContent: CsstsAtoms['widthFitContent']
  const widthIntrinsic: CsstsAtoms['widthIntrinsic']
  const widthMaxContent: CsstsAtoms['widthMaxContent']
  const widthMinContent: CsstsAtoms['widthMinContent']
  const widthMinIntrinsic: CsstsAtoms['widthMinIntrinsic']
  const widthStretch: CsstsAtoms['widthStretch']
  const width0: CsstsAtoms['width0']
  const width24: CsstsAtoms['width24']
  const width32: CsstsAtoms['width32']
  const width40: CsstsAtoms['width40']
  const width48: CsstsAtoms['width48']
  const width64: CsstsAtoms['width64']
  const width80: CsstsAtoms['width80']
  const width100: CsstsAtoms['width100']
  const width120: CsstsAtoms['width120']
  const width160: CsstsAtoms['width160']
  const width200: CsstsAtoms['width200']
  const width240: CsstsAtoms['width240']
  const width320: CsstsAtoms['width320']
  const widthFull: CsstsAtoms['widthFull']
  const widthHalf: CsstsAtoms['widthHalf']
  const widthScreen: CsstsAtoms['widthScreen']

  // ==================== height ====================
  const heightAuto: CsstsAtoms['heightAuto']
  const heightFitContent: CsstsAtoms['heightFitContent']
  const heightIntrinsic: CsstsAtoms['heightIntrinsic']
  const heightMaxContent: CsstsAtoms['heightMaxContent']
  const heightMinContent: CsstsAtoms['heightMinContent']
  const heightMinIntrinsic: CsstsAtoms['heightMinIntrinsic']
  const heightStretch: CsstsAtoms['heightStretch']
  const height0: CsstsAtoms['height0']
  const height24: CsstsAtoms['height24']
  const height32: CsstsAtoms['height32']
  const height40: CsstsAtoms['height40']
  const height48: CsstsAtoms['height48']
  const height64: CsstsAtoms['height64']
  const height80: CsstsAtoms['height80']
  const height100: CsstsAtoms['height100']
  const height120: CsstsAtoms['height120']
  const heightFull: CsstsAtoms['heightFull']
  const heightHalf: CsstsAtoms['heightHalf']
  const heightScreen: CsstsAtoms['heightScreen']

  // ==================== min-width ====================
  const minWidthAuto: CsstsAtoms['minWidthAuto']
  const minWidthFitContent: CsstsAtoms['minWidthFitContent']
  const minWidthIntrinsic: CsstsAtoms['minWidthIntrinsic']
  const minWidthMaxContent: CsstsAtoms['minWidthMaxContent']
  const minWidthMinContent: CsstsAtoms['minWidthMinContent']
  const minWidthMinIntrinsic: CsstsAtoms['minWidthMinIntrinsic']
  const minWidthStretch: CsstsAtoms['minWidthStretch']

  // ==================== max-width ====================
  const maxWidthFitContent: CsstsAtoms['maxWidthFitContent']
  const maxWidthIntrinsic: CsstsAtoms['maxWidthIntrinsic']
  const maxWidthMaxContent: CsstsAtoms['maxWidthMaxContent']
  const maxWidthMinContent: CsstsAtoms['maxWidthMinContent']
  const maxWidthMinIntrinsic: CsstsAtoms['maxWidthMinIntrinsic']
  const maxWidthNone: CsstsAtoms['maxWidthNone']
  const maxWidthStretch: CsstsAtoms['maxWidthStretch']

  // ==================== min-height ====================
  const minHeightAuto: CsstsAtoms['minHeightAuto']
  const minHeightFitContent: CsstsAtoms['minHeightFitContent']
  const minHeightIntrinsic: CsstsAtoms['minHeightIntrinsic']
  const minHeightMaxContent: CsstsAtoms['minHeightMaxContent']
  const minHeightMinContent: CsstsAtoms['minHeightMinContent']
  const minHeightMinIntrinsic: CsstsAtoms['minHeightMinIntrinsic']
  const minHeightStretch: CsstsAtoms['minHeightStretch']

  // ==================== max-height ====================
  const maxHeightFitContent: CsstsAtoms['maxHeightFitContent']
  const maxHeightIntrinsic: CsstsAtoms['maxHeightIntrinsic']
  const maxHeightMaxContent: CsstsAtoms['maxHeightMaxContent']
  const maxHeightMinContent: CsstsAtoms['maxHeightMinContent']
  const maxHeightMinIntrinsic: CsstsAtoms['maxHeightMinIntrinsic']
  const maxHeightNone: CsstsAtoms['maxHeightNone']
  const maxHeightStretch: CsstsAtoms['maxHeightStretch']

  // ==================== padding ====================
  const padding0: CsstsAtoms['padding0']
  const padding2: CsstsAtoms['padding2']
  const padding4: CsstsAtoms['padding4']
  const padding6: CsstsAtoms['padding6']
  const padding8: CsstsAtoms['padding8']
  const padding10: CsstsAtoms['padding10']
  const padding12: CsstsAtoms['padding12']
  const padding14: CsstsAtoms['padding14']
  const padding16: CsstsAtoms['padding16']
  const padding20: CsstsAtoms['padding20']
  const padding24: CsstsAtoms['padding24']
  const padding32: CsstsAtoms['padding32']
  const padding40: CsstsAtoms['padding40']
  const padding48: CsstsAtoms['padding48']
  const padding64: CsstsAtoms['padding64']

  // ==================== margin ====================
  const marginAuto: CsstsAtoms['marginAuto']
  const margin0: CsstsAtoms['margin0']
  const margin2: CsstsAtoms['margin2']
  const margin4: CsstsAtoms['margin4']
  const margin6: CsstsAtoms['margin6']
  const margin8: CsstsAtoms['margin8']
  const margin10: CsstsAtoms['margin10']
  const margin12: CsstsAtoms['margin12']
  const margin14: CsstsAtoms['margin14']
  const margin16: CsstsAtoms['margin16']
  const margin20: CsstsAtoms['margin20']
  const margin24: CsstsAtoms['margin24']
  const margin32: CsstsAtoms['margin32']
  const margin40: CsstsAtoms['margin40']
  const margin48: CsstsAtoms['margin48']
  const margin64: CsstsAtoms['margin64']

  // ==================== gap ====================
  const gap0: CsstsAtoms['gap0']
  const gap2: CsstsAtoms['gap2']
  const gap4: CsstsAtoms['gap4']
  const gap6: CsstsAtoms['gap6']
  const gap8: CsstsAtoms['gap8']
  const gap10: CsstsAtoms['gap10']
  const gap12: CsstsAtoms['gap12']
  const gap16: CsstsAtoms['gap16']
  const gap20: CsstsAtoms['gap20']
  const gap24: CsstsAtoms['gap24']
  const gap32: CsstsAtoms['gap32']

  // ==================== font-size ====================
  const fontSizeLarge: CsstsAtoms['fontSizeLarge']
  const fontSizeLarger: CsstsAtoms['fontSizeLarger']
  const fontSizeMedium: CsstsAtoms['fontSizeMedium']
  const fontSizeSmall: CsstsAtoms['fontSizeSmall']
  const fontSizeSmaller: CsstsAtoms['fontSizeSmaller']
  const fontSizeXLarge: CsstsAtoms['fontSizeXLarge']
  const fontSizeXSmall: CsstsAtoms['fontSizeXSmall']
  const fontSizeXxLarge: CsstsAtoms['fontSizeXxLarge']
  const fontSizeXxSmall: CsstsAtoms['fontSizeXxSmall']
  const fontSizeXxxLarge: CsstsAtoms['fontSizeXxxLarge']
  const fontSize10: CsstsAtoms['fontSize10']
  const fontSize11: CsstsAtoms['fontSize11']
  const fontSize12: CsstsAtoms['fontSize12']
  const fontSize13: CsstsAtoms['fontSize13']
  const fontSize14: CsstsAtoms['fontSize14']
  const fontSize15: CsstsAtoms['fontSize15']
  const fontSize16: CsstsAtoms['fontSize16']
  const fontSize18: CsstsAtoms['fontSize18']
  const fontSize20: CsstsAtoms['fontSize20']
  const fontSize24: CsstsAtoms['fontSize24']
  const fontSize28: CsstsAtoms['fontSize28']
  const fontSize32: CsstsAtoms['fontSize32']
  const fontSize36: CsstsAtoms['fontSize36']
  const fontSize48: CsstsAtoms['fontSize48']

  // ==================== font-weight ====================
  const fontWeightBold: CsstsAtoms['fontWeightBold']
  const fontWeightBolder: CsstsAtoms['fontWeightBolder']
  const fontWeightLighter: CsstsAtoms['fontWeightLighter']
  const fontWeightNormal: CsstsAtoms['fontWeightNormal']

  // ==================== font-style ====================
  const fontStyleItalic: CsstsAtoms['fontStyleItalic']
  const fontStyleNormal: CsstsAtoms['fontStyleNormal']
  const fontStyleOblique: CsstsAtoms['fontStyleOblique']

  // ==================== line-height ====================
  const lineHeightNormal: CsstsAtoms['lineHeightNormal']
  const lineHeight1: CsstsAtoms['lineHeight1']
  const lineHeight1p25: CsstsAtoms['lineHeight1p25']
  const lineHeight1p5: CsstsAtoms['lineHeight1p5']
  const lineHeight1p75: CsstsAtoms['lineHeight1p75']
  const lineHeight2: CsstsAtoms['lineHeight2']

  // ==================== text-align ====================
  const textAlignCenter: CsstsAtoms['textAlignCenter']
  const textAlignEnd: CsstsAtoms['textAlignEnd']
  const textAlignJustify: CsstsAtoms['textAlignJustify']
  const textAlignLeft: CsstsAtoms['textAlignLeft']
  const textAlignMatchParent: CsstsAtoms['textAlignMatchParent']
  const textAlignRight: CsstsAtoms['textAlignRight']
  const textAlignStart: CsstsAtoms['textAlignStart']

  // ==================== text-transform ====================
  const textTransformCapitalize: CsstsAtoms['textTransformCapitalize']
  const textTransformFullSizeKana: CsstsAtoms['textTransformFullSizeKana']
  const textTransformFullWidth: CsstsAtoms['textTransformFullWidth']
  const textTransformLowercase: CsstsAtoms['textTransformLowercase']
  const textTransformNone: CsstsAtoms['textTransformNone']
  const textTransformUppercase: CsstsAtoms['textTransformUppercase']

  // ==================== white-space ====================
  const whiteSpaceBreakSpaces: CsstsAtoms['whiteSpaceBreakSpaces']
  const whiteSpaceNormal: CsstsAtoms['whiteSpaceNormal']
  const whiteSpaceNowrap: CsstsAtoms['whiteSpaceNowrap']
  const whiteSpacePre: CsstsAtoms['whiteSpacePre']
  const whiteSpacePreLine: CsstsAtoms['whiteSpacePreLine']
  const whiteSpacePreWrap: CsstsAtoms['whiteSpacePreWrap']

  // ==================== word-break ====================
  const wordBreakAutoPhrase: CsstsAtoms['wordBreakAutoPhrase']
  const wordBreakBreakAll: CsstsAtoms['wordBreakBreakAll']
  const wordBreakBreakWord: CsstsAtoms['wordBreakBreakWord']
  const wordBreakKeepAll: CsstsAtoms['wordBreakKeepAll']
  const wordBreakNormal: CsstsAtoms['wordBreakNormal']

  // ==================== overflow-wrap ====================
  const overflowWrapAnywhere: CsstsAtoms['overflowWrapAnywhere']
  const overflowWrapBreakWord: CsstsAtoms['overflowWrapBreakWord']
  const overflowWrapNormal: CsstsAtoms['overflowWrapNormal']

  // ==================== vertical-align ====================
  const verticalAlignBaseline: CsstsAtoms['verticalAlignBaseline']
  const verticalAlignBottom: CsstsAtoms['verticalAlignBottom']
  const verticalAlignMiddle: CsstsAtoms['verticalAlignMiddle']
  const verticalAlignSub: CsstsAtoms['verticalAlignSub']
  const verticalAlignSuper: CsstsAtoms['verticalAlignSuper']
  const verticalAlignTextBottom: CsstsAtoms['verticalAlignTextBottom']
  const verticalAlignTextTop: CsstsAtoms['verticalAlignTextTop']
  const verticalAlignTop: CsstsAtoms['verticalAlignTop']

  // ==================== border-style ====================
  const borderStyleDashed: CsstsAtoms['borderStyleDashed']
  const borderStyleDotted: CsstsAtoms['borderStyleDotted']
  const borderStyleDouble: CsstsAtoms['borderStyleDouble']
  const borderStyleGroove: CsstsAtoms['borderStyleGroove']
  const borderStyleHidden: CsstsAtoms['borderStyleHidden']
  const borderStyleInset: CsstsAtoms['borderStyleInset']
  const borderStyleNone: CsstsAtoms['borderStyleNone']
  const borderStyleOutset: CsstsAtoms['borderStyleOutset']
  const borderStyleRidge: CsstsAtoms['borderStyleRidge']
  const borderStyleSolid: CsstsAtoms['borderStyleSolid']

  // ==================== border-radius ====================
  const borderRadius0: CsstsAtoms['borderRadius0']
  const borderRadius2: CsstsAtoms['borderRadius2']
  const borderRadius4: CsstsAtoms['borderRadius4']
  const borderRadius6: CsstsAtoms['borderRadius6']
  const borderRadius8: CsstsAtoms['borderRadius8']
  const borderRadius12: CsstsAtoms['borderRadius12']
  const borderRadius16: CsstsAtoms['borderRadius16']
  const borderRadius9999: CsstsAtoms['borderRadius9999']

  // ==================== box-shadow ====================
  const boxShadowAccentColor: CsstsAtoms['boxShadowAccentColor']
  const boxShadowAccentColorText: CsstsAtoms['boxShadowAccentColorText']
  const boxShadowActiveText: CsstsAtoms['boxShadowActiveText']
  const boxShadowButtonBorder: CsstsAtoms['boxShadowButtonBorder']
  const boxShadowButtonFace: CsstsAtoms['boxShadowButtonFace']
  const boxShadowButtonText: CsstsAtoms['boxShadowButtonText']
  const boxShadowCanvas: CsstsAtoms['boxShadowCanvas']
  const boxShadowCanvasText: CsstsAtoms['boxShadowCanvasText']
  const boxShadowField: CsstsAtoms['boxShadowField']
  const boxShadowFieldText: CsstsAtoms['boxShadowFieldText']
  const boxShadowGrayText: CsstsAtoms['boxShadowGrayText']
  const boxShadowHighlight: CsstsAtoms['boxShadowHighlight']
  const boxShadowHighlightText: CsstsAtoms['boxShadowHighlightText']
  const boxShadowLinkText: CsstsAtoms['boxShadowLinkText']
  const boxShadowMark: CsstsAtoms['boxShadowMark']
  const boxShadowMarkText: CsstsAtoms['boxShadowMarkText']
  const boxShadowSelectedItem: CsstsAtoms['boxShadowSelectedItem']
  const boxShadowSelectedItemText: CsstsAtoms['boxShadowSelectedItemText']
  const boxShadowVisitedText: CsstsAtoms['boxShadowVisitedText']
  const boxShadowA98Rgb: CsstsAtoms['boxShadowA98Rgb']
  const boxShadowAliceblue: CsstsAtoms['boxShadowAliceblue']
  const boxShadowAntiquewhite: CsstsAtoms['boxShadowAntiquewhite']
  const boxShadowAqua: CsstsAtoms['boxShadowAqua']
  const boxShadowAquamarine: CsstsAtoms['boxShadowAquamarine']
  const boxShadowAzure: CsstsAtoms['boxShadowAzure']
  const boxShadowBeige: CsstsAtoms['boxShadowBeige']
  const boxShadowBisque: CsstsAtoms['boxShadowBisque']
  const boxShadowBlack: CsstsAtoms['boxShadowBlack']
  const boxShadowBlanchedalmond: CsstsAtoms['boxShadowBlanchedalmond']
  const boxShadowBlue: CsstsAtoms['boxShadowBlue']
  const boxShadowBlueviolet: CsstsAtoms['boxShadowBlueviolet']
  const boxShadowBrown: CsstsAtoms['boxShadowBrown']
  const boxShadowBurlywood: CsstsAtoms['boxShadowBurlywood']
  const boxShadowCadetblue: CsstsAtoms['boxShadowCadetblue']
  const boxShadowChartreuse: CsstsAtoms['boxShadowChartreuse']
  const boxShadowChocolate: CsstsAtoms['boxShadowChocolate']
  const boxShadowCoral: CsstsAtoms['boxShadowCoral']
  const boxShadowCornflowerblue: CsstsAtoms['boxShadowCornflowerblue']
  const boxShadowCornsilk: CsstsAtoms['boxShadowCornsilk']
  const boxShadowCrimson: CsstsAtoms['boxShadowCrimson']
  const boxShadowCurrentColor: CsstsAtoms['boxShadowCurrentColor']
  const boxShadowCyan: CsstsAtoms['boxShadowCyan']
  const boxShadowDarkblue: CsstsAtoms['boxShadowDarkblue']
  const boxShadowDarkcyan: CsstsAtoms['boxShadowDarkcyan']
  const boxShadowDarkgoldenrod: CsstsAtoms['boxShadowDarkgoldenrod']
  const boxShadowDarkgray: CsstsAtoms['boxShadowDarkgray']
  const boxShadowDarkgreen: CsstsAtoms['boxShadowDarkgreen']
  const boxShadowDarkgrey: CsstsAtoms['boxShadowDarkgrey']
  const boxShadowDarkkhaki: CsstsAtoms['boxShadowDarkkhaki']
  const boxShadowDarkmagenta: CsstsAtoms['boxShadowDarkmagenta']
  const boxShadowDarkolivegreen: CsstsAtoms['boxShadowDarkolivegreen']
  const boxShadowDarkorange: CsstsAtoms['boxShadowDarkorange']
  const boxShadowDarkorchid: CsstsAtoms['boxShadowDarkorchid']
  const boxShadowDarkred: CsstsAtoms['boxShadowDarkred']
  const boxShadowDarksalmon: CsstsAtoms['boxShadowDarksalmon']
  const boxShadowDarkseagreen: CsstsAtoms['boxShadowDarkseagreen']
  const boxShadowDarkslateblue: CsstsAtoms['boxShadowDarkslateblue']
  const boxShadowDarkslategray: CsstsAtoms['boxShadowDarkslategray']
  const boxShadowDarkslategrey: CsstsAtoms['boxShadowDarkslategrey']
  const boxShadowDarkturquoise: CsstsAtoms['boxShadowDarkturquoise']
  const boxShadowDarkviolet: CsstsAtoms['boxShadowDarkviolet']
  const boxShadowDecreasing: CsstsAtoms['boxShadowDecreasing']
  const boxShadowDeeppink: CsstsAtoms['boxShadowDeeppink']
  const boxShadowDeepskyblue: CsstsAtoms['boxShadowDeepskyblue']
  const boxShadowDimgray: CsstsAtoms['boxShadowDimgray']
  const boxShadowDimgrey: CsstsAtoms['boxShadowDimgrey']
  const boxShadowDisplayP3: CsstsAtoms['boxShadowDisplayP3']
  const boxShadowDodgerblue: CsstsAtoms['boxShadowDodgerblue']
  const boxShadowFirebrick: CsstsAtoms['boxShadowFirebrick']
  const boxShadowFloralwhite: CsstsAtoms['boxShadowFloralwhite']
  const boxShadowForestgreen: CsstsAtoms['boxShadowForestgreen']
  const boxShadowFuchsia: CsstsAtoms['boxShadowFuchsia']
  const boxShadowGainsboro: CsstsAtoms['boxShadowGainsboro']
  const boxShadowGhostwhite: CsstsAtoms['boxShadowGhostwhite']
  const boxShadowGold: CsstsAtoms['boxShadowGold']
  const boxShadowGoldenrod: CsstsAtoms['boxShadowGoldenrod']
  const boxShadowGray: CsstsAtoms['boxShadowGray']
  const boxShadowGreen: CsstsAtoms['boxShadowGreen']
  const boxShadowGreenyellow: CsstsAtoms['boxShadowGreenyellow']
  const boxShadowGrey: CsstsAtoms['boxShadowGrey']
  const boxShadowHoneydew: CsstsAtoms['boxShadowHoneydew']
  const boxShadowHotpink: CsstsAtoms['boxShadowHotpink']
  const boxShadowHsl: CsstsAtoms['boxShadowHsl']
  const boxShadowHue: CsstsAtoms['boxShadowHue']
  const boxShadowHwb: CsstsAtoms['boxShadowHwb']
  const boxShadowIn: CsstsAtoms['boxShadowIn']
  const boxShadowIncreasing: CsstsAtoms['boxShadowIncreasing']
  const boxShadowIndianred: CsstsAtoms['boxShadowIndianred']
  const boxShadowIndigo: CsstsAtoms['boxShadowIndigo']
  const boxShadowInset: CsstsAtoms['boxShadowInset']
  const boxShadowIvory: CsstsAtoms['boxShadowIvory']
  const boxShadowKhaki: CsstsAtoms['boxShadowKhaki']
  const boxShadowLab: CsstsAtoms['boxShadowLab']
  const boxShadowLavender: CsstsAtoms['boxShadowLavender']
  const boxShadowLavenderblush: CsstsAtoms['boxShadowLavenderblush']
  const boxShadowLawngreen: CsstsAtoms['boxShadowLawngreen']
  const boxShadowLch: CsstsAtoms['boxShadowLch']
  const boxShadowLemonchiffon: CsstsAtoms['boxShadowLemonchiffon']
  const boxShadowLightblue: CsstsAtoms['boxShadowLightblue']
  const boxShadowLightcoral: CsstsAtoms['boxShadowLightcoral']
  const boxShadowLightcyan: CsstsAtoms['boxShadowLightcyan']
  const boxShadowLightgoldenrodyellow: CsstsAtoms['boxShadowLightgoldenrodyellow']
  const boxShadowLightgray: CsstsAtoms['boxShadowLightgray']
  const boxShadowLightgreen: CsstsAtoms['boxShadowLightgreen']
  const boxShadowLightgrey: CsstsAtoms['boxShadowLightgrey']
  const boxShadowLightpink: CsstsAtoms['boxShadowLightpink']
  const boxShadowLightsalmon: CsstsAtoms['boxShadowLightsalmon']
  const boxShadowLightseagreen: CsstsAtoms['boxShadowLightseagreen']
  const boxShadowLightskyblue: CsstsAtoms['boxShadowLightskyblue']
  const boxShadowLightslategray: CsstsAtoms['boxShadowLightslategray']
  const boxShadowLightslategrey: CsstsAtoms['boxShadowLightslategrey']
  const boxShadowLightsteelblue: CsstsAtoms['boxShadowLightsteelblue']
  const boxShadowLightyellow: CsstsAtoms['boxShadowLightyellow']
  const boxShadowLime: CsstsAtoms['boxShadowLime']
  const boxShadowLimegreen: CsstsAtoms['boxShadowLimegreen']
  const boxShadowLinen: CsstsAtoms['boxShadowLinen']
  const boxShadowLonger: CsstsAtoms['boxShadowLonger']
  const boxShadowMagenta: CsstsAtoms['boxShadowMagenta']
  const boxShadowMaroon: CsstsAtoms['boxShadowMaroon']
  const boxShadowMediumaquamarine: CsstsAtoms['boxShadowMediumaquamarine']
  const boxShadowMediumblue: CsstsAtoms['boxShadowMediumblue']
  const boxShadowMediumorchid: CsstsAtoms['boxShadowMediumorchid']
  const boxShadowMediumpurple: CsstsAtoms['boxShadowMediumpurple']
  const boxShadowMediumseagreen: CsstsAtoms['boxShadowMediumseagreen']
  const boxShadowMediumslateblue: CsstsAtoms['boxShadowMediumslateblue']
  const boxShadowMediumspringgreen: CsstsAtoms['boxShadowMediumspringgreen']
  const boxShadowMediumturquoise: CsstsAtoms['boxShadowMediumturquoise']
  const boxShadowMediumvioletred: CsstsAtoms['boxShadowMediumvioletred']
  const boxShadowMidnightblue: CsstsAtoms['boxShadowMidnightblue']
  const boxShadowMintcream: CsstsAtoms['boxShadowMintcream']
  const boxShadowMistyrose: CsstsAtoms['boxShadowMistyrose']
  const boxShadowMoccasin: CsstsAtoms['boxShadowMoccasin']
  const boxShadowNavajowhite: CsstsAtoms['boxShadowNavajowhite']
  const boxShadowNavy: CsstsAtoms['boxShadowNavy']
  const boxShadowNone: CsstsAtoms['boxShadowNone']
  const boxShadowOklab: CsstsAtoms['boxShadowOklab']
  const boxShadowOklch: CsstsAtoms['boxShadowOklch']
  const boxShadowOldlace: CsstsAtoms['boxShadowOldlace']
  const boxShadowOlive: CsstsAtoms['boxShadowOlive']
  const boxShadowOlivedrab: CsstsAtoms['boxShadowOlivedrab']
  const boxShadowOrange: CsstsAtoms['boxShadowOrange']
  const boxShadowOrangered: CsstsAtoms['boxShadowOrangered']
  const boxShadowOrchid: CsstsAtoms['boxShadowOrchid']
  const boxShadowPalegoldenrod: CsstsAtoms['boxShadowPalegoldenrod']
  const boxShadowPalegreen: CsstsAtoms['boxShadowPalegreen']
  const boxShadowPaleturquoise: CsstsAtoms['boxShadowPaleturquoise']
  const boxShadowPalevioletred: CsstsAtoms['boxShadowPalevioletred']
  const boxShadowPapayawhip: CsstsAtoms['boxShadowPapayawhip']
  const boxShadowPeachpuff: CsstsAtoms['boxShadowPeachpuff']
  const boxShadowPeru: CsstsAtoms['boxShadowPeru']
  const boxShadowPink: CsstsAtoms['boxShadowPink']
  const boxShadowPlum: CsstsAtoms['boxShadowPlum']
  const boxShadowPowderblue: CsstsAtoms['boxShadowPowderblue']
  const boxShadowProphotoRgb: CsstsAtoms['boxShadowProphotoRgb']
  const boxShadowPurple: CsstsAtoms['boxShadowPurple']
  const boxShadowRebeccapurple: CsstsAtoms['boxShadowRebeccapurple']
  const boxShadowRec2020: CsstsAtoms['boxShadowRec2020']
  const boxShadowRed: CsstsAtoms['boxShadowRed']
  const boxShadowRosybrown: CsstsAtoms['boxShadowRosybrown']
  const boxShadowRoyalblue: CsstsAtoms['boxShadowRoyalblue']
  const boxShadowSaddlebrown: CsstsAtoms['boxShadowSaddlebrown']
  const boxShadowSalmon: CsstsAtoms['boxShadowSalmon']
  const boxShadowSandybrown: CsstsAtoms['boxShadowSandybrown']
  const boxShadowSeagreen: CsstsAtoms['boxShadowSeagreen']
  const boxShadowSeashell: CsstsAtoms['boxShadowSeashell']
  const boxShadowShorter: CsstsAtoms['boxShadowShorter']
  const boxShadowSienna: CsstsAtoms['boxShadowSienna']
  const boxShadowSilver: CsstsAtoms['boxShadowSilver']
  const boxShadowSkyblue: CsstsAtoms['boxShadowSkyblue']
  const boxShadowSlateblue: CsstsAtoms['boxShadowSlateblue']
  const boxShadowSlategray: CsstsAtoms['boxShadowSlategray']
  const boxShadowSlategrey: CsstsAtoms['boxShadowSlategrey']
  const boxShadowSnow: CsstsAtoms['boxShadowSnow']
  const boxShadowSpringgreen: CsstsAtoms['boxShadowSpringgreen']
  const boxShadowSrgb: CsstsAtoms['boxShadowSrgb']
  const boxShadowSrgbLinear: CsstsAtoms['boxShadowSrgbLinear']
  const boxShadowSteelblue: CsstsAtoms['boxShadowSteelblue']
  const boxShadowTan: CsstsAtoms['boxShadowTan']
  const boxShadowTeal: CsstsAtoms['boxShadowTeal']
  const boxShadowThistle: CsstsAtoms['boxShadowThistle']
  const boxShadowTomato: CsstsAtoms['boxShadowTomato']
  const boxShadowTransparent: CsstsAtoms['boxShadowTransparent']
  const boxShadowTurquoise: CsstsAtoms['boxShadowTurquoise']
  const boxShadowViolet: CsstsAtoms['boxShadowViolet']
  const boxShadowWheat: CsstsAtoms['boxShadowWheat']
  const boxShadowWhite: CsstsAtoms['boxShadowWhite']
  const boxShadowWhitesmoke: CsstsAtoms['boxShadowWhitesmoke']
  const boxShadowXyz: CsstsAtoms['boxShadowXyz']
  const boxShadowXyzD50: CsstsAtoms['boxShadowXyzD50']
  const boxShadowXyzD65: CsstsAtoms['boxShadowXyzD65']
  const boxShadowYellow: CsstsAtoms['boxShadowYellow']
  const boxShadowYellowgreen: CsstsAtoms['boxShadowYellowgreen']

  // ==================== opacity ====================
  const opacity0: CsstsAtoms['opacity0']
  const opacity0p25: CsstsAtoms['opacity0p25']
  const opacity0p5: CsstsAtoms['opacity0p5']
  const opacity0p75: CsstsAtoms['opacity0p75']
  const opacity1: CsstsAtoms['opacity1']

  // ==================== visibility ====================
  const visibilityCollapse: CsstsAtoms['visibilityCollapse']
  const visibilityHidden: CsstsAtoms['visibilityHidden']
  const visibilityVisible: CsstsAtoms['visibilityVisible']

  // ==================== overflow ====================
  const overflowAuto: CsstsAtoms['overflowAuto']
  const overflowClip: CsstsAtoms['overflowClip']
  const overflowHidden: CsstsAtoms['overflowHidden']
  const overflowOverlay: CsstsAtoms['overflowOverlay']
  const overflowScroll: CsstsAtoms['overflowScroll']
  const overflowVisible: CsstsAtoms['overflowVisible']

  // ==================== overflow-x ====================
  const overflowXAuto: CsstsAtoms['overflowXAuto']
  const overflowXClip: CsstsAtoms['overflowXClip']
  const overflowXHidden: CsstsAtoms['overflowXHidden']
  const overflowXScroll: CsstsAtoms['overflowXScroll']
  const overflowXVisible: CsstsAtoms['overflowXVisible']

  // ==================== overflow-y ====================
  const overflowYAuto: CsstsAtoms['overflowYAuto']
  const overflowYClip: CsstsAtoms['overflowYClip']
  const overflowYHidden: CsstsAtoms['overflowYHidden']
  const overflowYScroll: CsstsAtoms['overflowYScroll']
  const overflowYVisible: CsstsAtoms['overflowYVisible']

  // ==================== cursor ====================
  const cursorAlias: CsstsAtoms['cursorAlias']
  const cursorAllScroll: CsstsAtoms['cursorAllScroll']
  const cursorAuto: CsstsAtoms['cursorAuto']
  const cursorCell: CsstsAtoms['cursorCell']
  const cursorColResize: CsstsAtoms['cursorColResize']
  const cursorContextMenu: CsstsAtoms['cursorContextMenu']
  const cursorCopy: CsstsAtoms['cursorCopy']
  const cursorCrosshair: CsstsAtoms['cursorCrosshair']
  const cursorDefault: CsstsAtoms['cursorDefault']
  const cursorEResize: CsstsAtoms['cursorEResize']
  const cursorEwResize: CsstsAtoms['cursorEwResize']
  const cursorGrab: CsstsAtoms['cursorGrab']
  const cursorGrabbing: CsstsAtoms['cursorGrabbing']
  const cursorHand: CsstsAtoms['cursorHand']
  const cursorHelp: CsstsAtoms['cursorHelp']
  const cursorMove: CsstsAtoms['cursorMove']
  const cursorNResize: CsstsAtoms['cursorNResize']
  const cursorNeResize: CsstsAtoms['cursorNeResize']
  const cursorNeswResize: CsstsAtoms['cursorNeswResize']
  const cursorNoDrop: CsstsAtoms['cursorNoDrop']
  const cursorNone: CsstsAtoms['cursorNone']
  const cursorNotAllowed: CsstsAtoms['cursorNotAllowed']
  const cursorNsResize: CsstsAtoms['cursorNsResize']
  const cursorNwResize: CsstsAtoms['cursorNwResize']
  const cursorNwseResize: CsstsAtoms['cursorNwseResize']
  const cursorPointer: CsstsAtoms['cursorPointer']
  const cursorProgress: CsstsAtoms['cursorProgress']
  const cursorRowResize: CsstsAtoms['cursorRowResize']
  const cursorSResize: CsstsAtoms['cursorSResize']
  const cursorSeResize: CsstsAtoms['cursorSeResize']
  const cursorSwResize: CsstsAtoms['cursorSwResize']
  const cursorText: CsstsAtoms['cursorText']
  const cursorVerticalText: CsstsAtoms['cursorVerticalText']
  const cursorWResize: CsstsAtoms['cursorWResize']
  const cursorWait: CsstsAtoms['cursorWait']
  const cursorZoomIn: CsstsAtoms['cursorZoomIn']
  const cursorZoomOut: CsstsAtoms['cursorZoomOut']

  // ==================== pointer-events ====================
  const pointerEventsAll: CsstsAtoms['pointerEventsAll']
  const pointerEventsAuto: CsstsAtoms['pointerEventsAuto']
  const pointerEventsFill: CsstsAtoms['pointerEventsFill']
  const pointerEventsInherit: CsstsAtoms['pointerEventsInherit']
  const pointerEventsNone: CsstsAtoms['pointerEventsNone']
  const pointerEventsPainted: CsstsAtoms['pointerEventsPainted']
  const pointerEventsStroke: CsstsAtoms['pointerEventsStroke']
  const pointerEventsVisible: CsstsAtoms['pointerEventsVisible']
  const pointerEventsVisibleFill: CsstsAtoms['pointerEventsVisibleFill']
  const pointerEventsVisiblePainted: CsstsAtoms['pointerEventsVisiblePainted']
  const pointerEventsVisibleStroke: CsstsAtoms['pointerEventsVisibleStroke']

  // ==================== user-select ====================
  const userSelectAll: CsstsAtoms['userSelectAll']
  const userSelectAuto: CsstsAtoms['userSelectAuto']
  const userSelectContain: CsstsAtoms['userSelectContain']
  const userSelectNone: CsstsAtoms['userSelectNone']
  const userSelectText: CsstsAtoms['userSelectText']

  // ==================== z-index ====================
  const zIndexAuto: CsstsAtoms['zIndexAuto']
  const zIndex0: CsstsAtoms['zIndex0']
  const zIndex10: CsstsAtoms['zIndex10']
  const zIndex20: CsstsAtoms['zIndex20']
  const zIndex30: CsstsAtoms['zIndex30']
  const zIndex40: CsstsAtoms['zIndex40']
  const zIndex50: CsstsAtoms['zIndex50']
  const zIndex100: CsstsAtoms['zIndex100']
  const zIndex999: CsstsAtoms['zIndex999']
  const zIndex9999: CsstsAtoms['zIndex9999']

  // ==================== state ====================
  const isDisabled: CsstsAtoms['isDisabled']
  const isLoading: CsstsAtoms['isLoading']
  const isActive: CsstsAtoms['isActive']
  const isFocus: CsstsAtoms['isFocus']
  const isHover: CsstsAtoms['isHover']
  const isSelected: CsstsAtoms['isSelected']
  const isError: CsstsAtoms['isError']
  const isSuccess: CsstsAtoms['isSuccess']
  const isWarning: CsstsAtoms['isWarning']

}

export {}