import type {SlimeFunctionParams, SlimeLParen, SlimeRParen, SlimeVariableDeclaration} from "./SlimeAstInterface.ts";

export enum SlimeAstType {
    Program = 'Program', // 整个脚本或模块的根节点类型
    ImportDeclaration = 'ImportDeclaration', // import 声明语句的节点类型
    ImportSpecifier = 'ImportSpecifier', // import 解构中的单个导入说明符
    ImportNamespaceSpecifier = 'ImportNamespaceSpecifier', // import * as foo 形式的说明符
    ImportDefaultSpecifier = 'ImportDefaultSpecifier', // import foo from 'bar' 中的默认说明符
    FunctionParams = 'FunctionParams', // 函数形参列表的节点类型
    ExportNamedDeclaration = 'ExportNamedDeclaration', // export {foo} 形式的命名导出声明
    FunctionDeclaration = 'FunctionDeclaration', // 普通函数声明节点
    ClassDeclaration = 'ClassDeclaration', // class Foo {} 的声明节点
    ClassExpression = 'ClassExpression', // 匿名或具名的 class 表达式节点
    ObjectExpression = 'ObjectExpression', // 对象字面量表达式
    Property = 'Property', // 对象字面量的属性节点
    ArgumentList = 'ArgumentList', // 函数调用实参列表
    ExportDefaultDeclaration = 'ExportDefaultDeclaration', // export default 声明
    ExportAllDeclaration = 'ExportAllDeclaration', // export * from 的导出声明
    MethodDefinition = 'MethodDefinition', // class 或对象中的方法定义
    ExpressionStatement = 'ExpressionStatement', // 表达式语句包装节点
    EmptyStatement = 'EmptyStatement', // 单独的分号语句
    VariableDeclaration = 'VariableDeclaration', // 变量声明语句
    SpreadElement = 'SpreadElement', // 展开元素 ...expr
    Identifier = 'Identifier', // 标识符节点
    PrivateIdentifier = 'PrivateIdentifier', // 私有字段标识符 #foo
    ObjectPattern = 'ObjectPattern', // 解构赋值中的对象模式
    ArrayPattern = 'ArrayPattern', // 解构赋值中的数组模式
    RestElement = 'RestElement', // 解构中的 rest 元素
    AssignmentPattern = 'AssignmentPattern', // 解构赋值中的默认值模式
    MemberExpression = 'MemberExpression', // obj.prop 或 obj['prop'] 表达式
    ArrayExpression = 'ArrayExpression', // 数组字面量表达式
    CallExpression = 'CallExpression', // 函数调用表达式
    ReturnStatement = 'ReturnStatement', // return 语句
    BlockStatement = 'BlockStatement', // 花括号包裹的语句块
    FunctionExpression = 'FunctionExpression', // function () {} 表达式
    VariableDeclarator = 'VariableDeclarator', // 变量声明中的单个声明项
    NumericLiteral = 'NumericLiteral', // 数字字面量
    StringLiteral = 'StringLiteral', // 字符串字面量
    BooleanLiteral = 'BooleanLiteral', // 布尔字面量
    NullLiteral = 'NullLiteral', // null 字面量
    EqualOperator = 'EqualOperator', // 赋值等号运算符节点
    VariableDeclarationKind = 'VariableDeclarationKind', // const/let/var 关键字节点
    From = 'From', // import/export from 中的 from 关键字
    Export = 'Export', // export 关键字节点
    Dot = 'Dot', // 成员访问中的点号
    LParen = 'LParen', // 左圆括号
    RParen = 'RParen', // 右圆括号
    LBrace = 'LBrace', // 左花括号
    RBrace = 'RBrace', // 右花括号
}
