/**
 * CSS Generator - Generates CSS from used atomic styles
 * 
 * This module generates CSS rules only for the atomic styles
 * that are actually used in the codebase (on-demand generation).
 */

import type { AtomUsage } from './atom-scanner'
import { atomToCssPropertyMap } from './atom-scanner'

/** CSS generation options */
export interface CssGeneratorOptions {
  /** Minify the output CSS */
  minify?: boolean
  /** Add source comments */
  sourceComments?: boolean
  /** CSS prefix for class names */
  prefix?: string
}

/** Convert camelCase to kebab-case */
function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

/** Generate CSS for a single atom */
export function generateAtomCss(
  atomName: string,
  options: CssGeneratorOptions = {}
): string | null {
  const mapping = atomToCssPropertyMap[atomName]
  if (!mapping) return null
  
  const { minify = false, sourceComments = false, prefix = '' } = options
  const className = prefix + toKebabCase(atomName)
  
  let css = ''
  
  if (sourceComments && !minify) {
    css += `/* ${atomName} */\n`
  }
  
  if (minify) {
    css += `.${className}{${mapping.property}:${mapping.value}}`
  } else {
    css += `.${className} {\n`
    css += `  ${mapping.property}: ${mapping.value};\n`
    css += `}\n`
  }
  
  return css
}

/** Generate CSS for multiple atoms */
export function generateCss(
  atoms: string[] | Map<string, AtomUsage>,
  options: CssGeneratorOptions = {}
): string {
  const atomNames = atoms instanceof Map 
    ? Array.from(atoms.keys())
    : atoms
  
  const { minify = false, sourceComments = false } = options
  const cssRules: string[] = []
  
  if (sourceComments && !minify) {
    cssRules.push('/* Generated by cssts-types CSS Generator */')
    cssRules.push(`/* Total atoms: ${atomNames.length} */`)
    cssRules.push('')
  }
  
  for (const atomName of atomNames) {
    const css = generateAtomCss(atomName, options)
    if (css) {
      cssRules.push(css)
    }
  }
  
  return minify ? cssRules.join('') : cssRules.join('\n')
}

/** Generate all available CSS (for development/reference) */
export function generateAllCss(options: CssGeneratorOptions = {}): string {
  return generateCss(Object.keys(atomToCssPropertyMap), options)
}

/** Generate CSS from atom usage map */
export function generateCssFromUsage(
  usageMap: Map<string, AtomUsage>,
  options: CssGeneratorOptions = {}
): string {
  const { minify = false, sourceComments = false } = options
  const cssRules: string[] = []
  
  if (sourceComments && !minify) {
    cssRules.push('/* Generated by cssts-types CSS Generator (On-Demand) */')
    cssRules.push(`/* Used atoms: ${usageMap.size} */`)
    cssRules.push('')
  }
  
  for (const [atomName, usage] of usageMap) {
    const css = generateAtomCss(atomName, options)
    if (css) {
      if (sourceComments && !minify) {
        cssRules.push(`/* Used in: ${usage.usedIn.length} file(s) */`)
      }
      cssRules.push(css)
    }
  }
  
  return minify ? cssRules.join('') : cssRules.join('\n')
}

export default { generateAtomCss, generateCss, generateAllCss, generateCssFromUsage }
