/**
 * 属性到数值类型的映射配置
 * 定义每个 CSS 属性支持的数值类型（unit + value）
 */

import type { NumericType } from './types'

/** 特殊值 0（无单位） */
const zero: NumericType = { unit: 'zero' }

/**
 * CSS 属性到数值类型的映射
 * 每个属性对应一个 NumericType[] 数组
 */
export const propertyNumericTypes: Record<string, NumericType[]> = {
  // ========== sizing ==========
  'height': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'max-height': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'max-width': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'min-height': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'min-width': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'width': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== spacing ==========
  'column-gap': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin-bottom': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin-left': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin-right': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin-top': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding-bottom': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding-left': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding-right': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding-top': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'row-gap': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== positioning ==========
  'bottom': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'left': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'right': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'top': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== layout ==========
  'flex-grow': [{ unit: 'unitless', value: 'number' }],
  'flex-shrink': [{ unit: 'unitless', value: 'number' }],
  'grid-area': [{ unit: 'unitless', value: 'integer' }],
  'grid-auto-columns': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'grid-auto-rows': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'grid-column': [{ unit: 'unitless', value: 'integer' }],
  'grid-column-end': [{ unit: 'unitless', value: 'integer' }],
  'grid-column-gap': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'grid-column-start': [{ unit: 'unitless', value: 'integer' }],
  'grid-row': [{ unit: 'unitless', value: 'integer' }],
  'grid-row-end': [{ unit: 'unitless', value: 'integer' }],
  'grid-row-gap': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'grid-row-start': [{ unit: 'unitless', value: 'integer' }],
  'grid-template': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'grid-template-columns': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'grid-template-rows': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'order': [{ unit: 'unitless', value: 'integer' }],
  'z-index': [{ unit: 'unitless', value: 'integer' }],

  // ========== typography ==========
  'font-feature-settings': [{ unit: 'unitless', value: 'integer' }],
  'font-size': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'font-size-adjust': [{ unit: 'unitless', value: 'number' }],
  'font-smooth': [zero, { unit: 'px', value: 'integer' }],
  'font-stretch': [{ unit: 'ratio', value: 'number' }],
  'font-style': [{ unit: 'deg', value: 'number' }],
  'font-variation-settings': [{ unit: 'unitless', value: 'number' }],
  'font-weight': [{ unit: 'unitless', value: 'integer' }],
  'letter-spacing': [zero, { unit: 'px', value: 'integer' }],
  'line-clamp': [{ unit: 'unitless', value: 'integer' }],
  'line-height': [zero, { unit: 'px', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'line-height-step': [zero, { unit: 'px', value: 'integer' }],
  'tab-size': [zero, { unit: 'px', value: 'integer' }, { unit: 'unitless', value: 'integer' }],
  'text-combine-upright': [{ unit: 'unitless', value: 'integer' }],
  'text-decoration-thickness': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'text-indent': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'text-shadow': [zero, { unit: 'px', value: 'integer' }],
  'text-size-adjust': [{ unit: 'ratio', value: 'number' }],
  'text-underline-offset': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'vertical-align': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'word-spacing': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== border ==========
  'border': [zero, { unit: 'px', value: 'integer' }],
  'border-bottom': [zero, { unit: 'px', value: 'integer' }],
  'border-bottom-left-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-bottom-right-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-bottom-width': [zero, { unit: 'px', value: 'integer' }],
  'border-end-end-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-end-start-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-image-outset': [zero, { unit: 'px', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'border-image-slice': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
  'border-image-width': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'border-left': [zero, { unit: 'px', value: 'integer' }],
  'border-left-width': [zero, { unit: 'px', value: 'integer' }],
  'border-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-right': [zero, { unit: 'px', value: 'integer' }],
  'border-right-width': [zero, { unit: 'px', value: 'integer' }],
  'border-spacing': [zero, { unit: 'px', value: 'integer' }],
  'border-start-end-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-start-start-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-top': [zero, { unit: 'px', value: 'integer' }],
  'border-top-left-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-top-right-radius': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-top-width': [zero, { unit: 'px', value: 'integer' }],
  'border-width': [zero, { unit: 'px', value: 'integer' }],
  'outline-offset': [zero, { unit: 'px', value: 'integer' }],
  'outline-width': [zero, { unit: 'px', value: 'integer' }],

  // ========== background ==========
  'background': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'background-position': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'background-position-x': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'background-position-y': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'background-size': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== opacity ==========
  'fill-opacity': [{ unit: 'unitless', value: 'number' }],
  'opacity': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],

  // ========== transform ==========
  'perspective': [zero, { unit: 'px', value: 'integer' }],
  'rotate': [zero, { unit: 'deg', value: 'number' }],
  'scale': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
  'transform-origin': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'translate': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== animation ==========
  'animation': [{ unit: 'ms', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'animation-delay': [zero, { unit: 'ms', value: 'integer' }],
  'animation-duration': [zero, { unit: 'ms', value: 'integer' }],
  'animation-iteration-count': [{ unit: 'unitless', value: 'number' }],
  'animation-range-end': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'animation-range-start': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'animation-timing-function': [{ unit: 'unitless', value: 'number' }],
  'transition': [{ unit: 'ms', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'transition-delay': [zero, { unit: 'ms', value: 'integer' }],
  'transition-duration': [zero, { unit: 'ms', value: 'integer' }],
  'transition-timing-function': [{ unit: 'unitless', value: 'number' }],

  // ========== scroll ==========
  'overflow-clip-margin': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-block': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-block-end': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-block-start': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-bottom': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-inline': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-inline-end': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-inline-start': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-left': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-right': [zero, { unit: 'px', value: 'integer' }],
  'scroll-margin-top': [zero, { unit: 'px', value: 'integer' }],
  'scroll-padding': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-block': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-block-end': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-block-start': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-bottom': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-inline': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-inline-end': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-inline-start': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-left': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-right': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-top': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-snap-coordinate': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-snap-destination': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-snap-points-x': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-snap-points-y': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== other ==========
  'aspect-ratio': [{ unit: 'unitless', value: 'number' }],
  'azimuth': [{ unit: 'deg', value: 'number' }],
  'baseline-shift': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'box-flex': [{ unit: 'unitless', value: 'number' }],
  'box-flex-group': [{ unit: 'unitless', value: 'integer' }],
  'box-ordinal-group': [{ unit: 'unitless', value: 'integer' }],
  'clip-path': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'column-count': [{ unit: 'unitless', value: 'integer' }],
  'column-width': [zero, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-block-size': [zero, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-height': [zero, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-inline-size': [zero, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-size': [zero, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-width': [zero, { unit: 'px', value: 'integer' }],
  'counter-increment': [{ unit: 'unitless', value: 'integer' }],
  'counter-reset': [{ unit: 'unitless', value: 'integer' }],
  'counter-set': [{ unit: 'unitless', value: 'integer' }],
  'cursor': [{ unit: 'unitless', value: 'number' }],
  'cx': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'cy': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'glyph-orientation-horizontal': [{ unit: 'deg', value: 'number' }],
  'glyph-orientation-vertical': [{ unit: 'deg', value: 'number' }],
  'hyphenate-limit-chars': [{ unit: 'unitless', value: 'integer' }],
  'image-orientation': [{ unit: 'deg', value: 'number' }],
  'initial-letter': [{ unit: 'unitless', value: 'number' }],
  'kerning': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'mask': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'mask-border-outset': [zero, { unit: 'px', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'mask-border-slice': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
  'mask-border-width': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'mask-position': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'mask-size': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'math-depth': [{ unit: 'unitless', value: 'integer' }],
  'max-lines': [{ unit: 'unitless', value: 'integer' }],
  'object-position': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'offset-anchor': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'offset-distance': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'offset-path': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'deg', value: 'number' }],
  'offset-position': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'offset-rotate': [{ unit: 'deg', value: 'number' }],
  'orphans': [{ unit: 'unitless', value: 'integer' }],
  'pause-after': [zero, { unit: 'ms', value: 'integer' }],
  'pause-before': [zero, { unit: 'ms', value: 'integer' }],
  'perspective-origin': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'r': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'rest-after': [zero, { unit: 'ms', value: 'integer' }],
  'rest-before': [zero, { unit: 'ms', value: 'integer' }],
  'rx': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'ry': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'shape-image-threshold': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
  'shape-margin': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'shape-outside': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'stroke-dasharray': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'stroke-dashoffset': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'stroke-miterlimit': [{ unit: 'unitless', value: 'number' }],
  'stroke-width': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'view-timeline-inset': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'voice-balance': [{ unit: 'unitless', value: 'number' }],
  'voice-duration': [zero, { unit: 'ms', value: 'integer' }],
  'voice-family': [{ unit: 'unitless', value: 'integer' }],
  'voice-pitch': [{ unit: 'ratio', value: 'number' }],
  'voice-range': [{ unit: 'ratio', value: 'number' }],
  'voice-rate': [{ unit: 'ratio', value: 'number' }],
  'widows': [{ unit: 'unitless', value: 'integer' }],
  'x': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'y': [zero, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'zoom': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
}
