/**
 * 属性到数值类型的映射配置
 * 定义每个 CSS 属性支持的数值类型（unit + value）
 */

import type { NumericType } from './types'

/**
 * CSS 属性到数值类型的映射
 * 每个属性对应一个 NumericType[] 数组
 */
export const propertyNumericTypes: Record<string, NumericType[]> = {
  // ========== sizing ==========
  'height': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'max-height': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'max-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'min-height': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'min-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== spacing ==========
  'column-gap': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin-bottom': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin-left': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin-right': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'margin-top': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding-bottom': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding-left': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding-right': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'padding-top': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'row-gap': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== positioning ==========
  'bottom': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'left': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'right': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'top': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== layout ==========
  'flex-grow': [{ unit: 'unitless', value: 'number' }],
  'flex-shrink': [{ unit: 'unitless', value: 'number' }],
  'grid-area': [{ unit: 'unitless', value: 'integer' }],
  'grid-auto-columns': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'grid-auto-rows': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'grid-column': [{ unit: 'unitless', value: 'integer' }],
  'grid-column-end': [{ unit: 'unitless', value: 'integer' }],
  'grid-column-gap': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'grid-column-start': [{ unit: 'unitless', value: 'integer' }],
  'grid-row': [{ unit: 'unitless', value: 'integer' }],
  'grid-row-end': [{ unit: 'unitless', value: 'integer' }],
  'grid-row-gap': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'grid-row-start': [{ unit: 'unitless', value: 'integer' }],
  'grid-template': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'grid-template-columns': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'grid-template-rows': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'fr', value: 'number' }],
  'order': [{ unit: 'unitless', value: 'integer' }],
  'z-index': [{ unit: 'unitless', value: 'integer' }],

  // ========== typography ==========
  'font-feature-settings': [{ unit: 'unitless', value: 'integer' }],
  'font-size': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'font-size-adjust': [{ unit: 'unitless', value: 'number' }],
  'font-smooth': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'font-stretch': [{ unit: 'ratio', value: 'number' }],
  'font-style': [{ unit: 'deg', value: 'number' }],
  'font-variation-settings': [{ unit: 'unitless', value: 'number' }],
  'font-weight': [{ unit: 'unitless', value: 'integer' }],
  'letter-spacing': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'line-clamp': [{ unit: 'unitless', value: 'integer' }],
  'line-height': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'line-height-step': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'tab-size': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'unitless', value: 'integer' }],
  'text-combine-upright': [{ unit: 'unitless', value: 'integer' }],
  'text-decoration-thickness': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'text-indent': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'text-shadow': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'text-size-adjust': [{ unit: 'ratio', value: 'number' }],
  'text-underline-offset': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'vertical-align': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'word-spacing': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== border ==========
  'border': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-bottom': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-bottom-left-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-bottom-right-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-bottom-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-end-end-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-end-start-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-image-outset': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'border-image-slice': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
  'border-image-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'border-left': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-left-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-right': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-right-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-spacing': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-start-end-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-start-start-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-top': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-top-left-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-top-right-radius': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'border-top-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'border-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'outline-offset': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'outline-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],

  // ========== background ==========
  'background': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'background-position': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'background-position-x': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'background-position-y': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'background-size': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== opacity ==========
  'fill-opacity': [{ unit: 'unitless', value: 'number' }],
  'opacity': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],

  // ========== transform ==========
  'perspective': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'rotate': [{ unit: 'zero', value: 'integer' }, { unit: 'deg', value: 'number' }],
  'scale': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
  'transform-origin': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'translate': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== animation ==========
  'animation': [{ unit: 'ms', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'animation-delay': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'animation-duration': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'animation-iteration-count': [{ unit: 'unitless', value: 'number' }],
  'animation-range-end': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'animation-range-start': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'animation-timing-function': [{ unit: 'unitless', value: 'number' }],
  'transition': [{ unit: 'ms', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'transition-delay': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'transition-duration': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'transition-timing-function': [{ unit: 'unitless', value: 'number' }],

  // ========== scroll ==========
  'overflow-clip-margin': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-block': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-block-end': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-block-start': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-bottom': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-inline': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-inline-end': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-inline-start': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-left': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-right': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-margin-top': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'scroll-padding': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-block': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-block-end': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-block-start': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-bottom': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-inline': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-inline-end': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-inline-start': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-left': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-right': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-padding-top': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-snap-coordinate': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-snap-destination': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-snap-points-x': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'scroll-snap-points-y': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],

  // ========== other ==========
  'aspect-ratio': [{ unit: 'unitless', value: 'number' }],
  'azimuth': [{ unit: 'deg', value: 'number' }],
  'baseline-shift': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'box-flex': [{ unit: 'unitless', value: 'number' }],
  'box-flex-group': [{ unit: 'unitless', value: 'integer' }],
  'box-ordinal-group': [{ unit: 'unitless', value: 'integer' }],
  'clip-path': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'column-count': [{ unit: 'unitless', value: 'integer' }],
  'column-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-block-size': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-height': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-inline-size': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-size': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'contain-intrinsic-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }],
  'counter-increment': [{ unit: 'unitless', value: 'integer' }],
  'counter-reset': [{ unit: 'unitless', value: 'integer' }],
  'counter-set': [{ unit: 'unitless', value: 'integer' }],
  'cursor': [{ unit: 'unitless', value: 'number' }],
  'cx': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'cy': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'glyph-orientation-horizontal': [{ unit: 'deg', value: 'number' }],
  'glyph-orientation-vertical': [{ unit: 'deg', value: 'number' }],
  'hyphenate-limit-chars': [{ unit: 'unitless', value: 'integer' }],
  'image-orientation': [{ unit: 'deg', value: 'number' }],
  'initial-letter': [{ unit: 'unitless', value: 'number' }],
  'kerning': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'mask': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'mask-border-outset': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'unitless', value: 'number' }],
  'mask-border-slice': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
  'mask-border-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'mask-position': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'mask-size': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'math-depth': [{ unit: 'unitless', value: 'integer' }],
  'max-lines': [{ unit: 'unitless', value: 'integer' }],
  'object-position': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'offset-anchor': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'offset-distance': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'offset-path': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'deg', value: 'number' }],
  'offset-position': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'offset-rotate': [{ unit: 'deg', value: 'number' }],
  'orphans': [{ unit: 'unitless', value: 'integer' }],
  'pause-after': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'pause-before': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'perspective-origin': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'r': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'rest-after': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'rest-before': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'rx': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'ry': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'shape-image-threshold': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
  'shape-margin': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'shape-outside': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'stroke-dasharray': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'stroke-dashoffset': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'stroke-miterlimit': [{ unit: 'unitless', value: 'number' }],
  'stroke-width': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }, { unit: 'unitless', value: 'number' }],
  'view-timeline-inset': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'voice-balance': [{ unit: 'unitless', value: 'number' }],
  'voice-duration': [{ unit: 'zero', value: 'integer' }, { unit: 'ms', value: 'integer' }],
  'voice-family': [{ unit: 'unitless', value: 'integer' }],
  'voice-pitch': [{ unit: 'ratio', value: 'number' }],
  'voice-range': [{ unit: 'ratio', value: 'number' }],
  'voice-rate': [{ unit: 'ratio', value: 'number' }],
  'widows': [{ unit: 'unitless', value: 'integer' }],
  'x': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'y': [{ unit: 'zero', value: 'integer' }, { unit: 'px', value: 'integer' }, { unit: 'ratio', value: 'number' }],
  'zoom': [{ unit: 'unitless', value: 'number' }, { unit: 'ratio', value: 'number' }],
}
